### ISSUE TITLE
Bug with Correction/Prediction Feature

### ISSUE THREAD

**Issue by ongweekeong** [CS2113-AY1819S1-F10-3/main#165]
Example:
Input command:
![image](https://user-images.githubusercontent.com/35793358/47762891-5ec90580-dcf9-11e8-9797-2f87ff0ff813.png)

Outcome:
![image](https://user-images.githubusercontent.com/35793358/47763008-c41cf680-dcf9-11e8-91b9-e52f99fa4757.png)

The same outcome can be reproduced whenever input commands are 1 character off from the valid input commands. For example, typing in "ad" (instead of "add") or "edi" (instead of "edit) or "ready" (instead of "read") will cause the UI to display a blank screen.

**Comment by ShreyasKp** [comment]
Bug due to clearscreen() added by @andyrobert3. Fixed bug by removing erroneous clearscreen() instruction.
